# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: botDB
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: botUser
      MYSQL_PASSWORD: botPassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
