* sBots

[[https://actions-badge.atrox.dev/benkio/sBots/goto][file:https://img.shields.io/endpoint.svg?url=https%3A%2F%2Factions-badge.atrox.dev%2Fbenkio%2FsBots%2Fbadge&style=flat]]
[[https://scala-steward.org][file:https://img.shields.io/badge/Scala_Steward-helping-blue.svg?style=flat&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAQCAMAAAARSr4IAAAAVFBMVEUAAACHjojlOy5NWlrKzcYRKjGFjIbp293YycuLa3pYY2LSqql4f3pCUFTgSjNodYRmcXUsPD/NTTbjRS+2jomhgnzNc223cGvZS0HaSD0XLjbaSjElhIr+AAAAAXRSTlMAQObYZgAAAHlJREFUCNdNyosOwyAIhWHAQS1Vt7a77/3fcxxdmv0xwmckutAR1nkm4ggbyEcg/wWmlGLDAA3oL50xi6fk5ffZ3E2E3QfZDCcCN2YtbEWZt+Drc6u6rlqv7Uk0LdKqqr5rk2UCRXOk0vmQKGfc94nOJyQjouF9H/wCc9gECEYfONoAAAAASUVORK5CYII=]]

  A repository containing the following bots developed in Scala.

  Author: https://t.me/Benkio

** Bots

     | Telegram Bot                     | Character Link |
     | https://t.me/RichardPHJBensonBot | [[https://en.wikipedia.org/wiki/Richard_Benson_(musician)][Richard Philip Henry John Benson]] |
     | https://t.me/YouTuboAncheI0Bot   | [[https://www.youtube.com/channel/UCO66DuFYNFMdR8Y31Ire1fg][Youtubo Anche Io]] |
     | https://t.me/ABarberoBot         | [[https://en.wikipedia.org/wiki/Alessandro_Barbero][Alessandro Barbero]] |
     | https://t.me/M0sconiBot          | [[https://en.wikipedia.org/wiki/Germano_Mosconi][Germano Mosconi]] |
     | https://t.me/XahLeeBot           | [[http://xahlee.info/][Xah Lee]] |
     | https://t.me/CalandroBot         | |

** Required Software
    - [[https://git-scm.com/][git]]
    - [[https://www.scala-sbt.org/][sbt - Scala Build Tool]]
    - [[https://www.scala-lang.org/][scala]]
    - [[https://www.openssl.org/][openSSL]]

** Add Data to the Bots

     Each bot contains a ~resources~ folder. You need to put in there
     the ~.token~ file containing the telegram key specific to each
     bot.

     Each  bot also uses a ~SQLite~ Database! So you need
     to provide the path to the database into the ~application.conf~
     or just set up the specific environment variables. No need to put
     the files in resources since those will be fetched from the web
     via URLs.

     Check [[https://youtu.be/T-AfAvJLSJE][this video]] for a complete rundown on how to add files to a bot.

** Database Setup

     There's a module called ~botDB~, if opportunely configured,
     when launched, it applies the migrations and populates a bot
     database. Just set up the ~application.conf~ correctly with the DB
     path, see the DB in the root of the project, and the location of
     the ~csv~. There should be a ~csv~ file at the root of each bot
     module

** Compile and Test

  Several command alias are defined in the project to group together useful ~sbt~ commands:
  - ~dbSetup~ :: Run the botDB main that set up the DB anew. Running the migrations and updating the media tables based on the CSV in the bots folders.
  - ~fix~ :: Run the ~scalafmt~ and ~scalafix~ in the whole project.
  - ~check~ :: Check the project for formatting and dependencies using ~sbt~ plugins such as ~scalafmt~.
  - ~validate~ :: compile clean and test. It includes the ~fix~ command and it is run in the CI.

  Moreover, there are tests excluded from the CI because they are quite slow. In this category, there is one that checks all the media links in the DB and can be called manually by ~sbt integration/runIntegrationScalaTests~

** Run the Bots
*** Long Polling
     Under Windows use the git bash terminal.

   #+begin_src bash
     ./lunch.sh # I know it's lunch not launch :)
   #+end_src

*** Webhook
**** Localhost

     - Export the webhook host, locally using [[https://ngrok.com/][ngrok]], [[https://github.com/beyondcode/expose][expose]] or [[https://github.com/agrinman/tunnelto][tunnelTo]]. example: ~./expose share http://localhost:8080~
     - Change the entry ~WEBHOOK_HOST_URL~ with the name of the host from the previous step or change it in ~~sBots/main/src/main/resources/application.conf~
     - run ~sbt assembly~
     - run ~java -cp main/target/scala-2.13/main.jar com.benkio.main.MainWebhook~

**** Docker

      TODO: There's already a ~main/Dockerfile~ with the command to run the webhook, but still it needs to be tested and visible from outside
            Also check [[https://expose.dev/docs/getting-started/installation#as-a-docker-container][expose on docker]]. In order to may make it discoverable from telegram API.

** Deploy on Oracle Cloud Infrastructure VM
*** Setup

 - Create a VM instance in the Oracle cloud
 - Get the SSH Private and Public Keys to access it
   - Login to ssh VM instance by ssh private key, user, and IP. get the last two on the site. Eg command: ~ssh -i <<private key of the vm>> <<user of the vm>>@<<public IP of the vm>>~ (~ssh -i ssh-key-2022-04-26.key opc@140.238.155.16~)
 - Install the jdk 16. Follow this [[https://blogs.oracle.com/developers/post/how-to-install-oracle-java-in-oracle-cloud-infrastructure][tutorial]]

**** Webhook Extra Configuration

  Eventually, the library connecting to Telegram should provide full SSL certificate support for [[https://github.com/apimorphism/telegramium/issues/348][this issue]], but until now we will rely on ~nginx~ and reverse proxy. Follow these steps to set up the server property:

  - Server Prerequisites :: Check [[https://core.telegram.org/bots/webhooks#the-short-version][this page]] for the prerequisites required by telegram to work with webhook. In our case, we choose port 8443 for SSL connection.
  - Open Port on OCI Subnet :: The instance where the bots are running needs to have an attached VNICs([[https://docs.oracle.com/iaas/Content/Network/Tasks/managingVNICs.htm][Virtual Network Interface Card]]) with a subnet. The subnet will have a default security list containing the rules for the ports available from outside. Add a new rule for the port required and save it. The parameters to use are:
    - Stateless: No
    - Source: 0.0.0.0
    - IP Protocol: TCP
    - Source Port Range: All
    - Destination Port Range: 8443
    This should allow telegram to reach your server through that port.
  - Generate a keystore JKS :: On the server, using the commands on [[https://core.telegram.org/bots/self-signed][this page]], follow the instruction for the java keystore, pasting each command one by one. Command: ~keytool -genkey -keyalg RSA -alias 129.152.27.196 -keystore sbotsKeystore.jks -storepass sbotsKeystorePassword -validity 360 -keysize 2048~
    When generating the keystore provide the following responses to the questions:
    - "first and last name": "Enrico Benini"
    - "organizational unit": "."
    - "organization": "Benkio"
    - "city or location": "Cesena"@
    - "state or province": "Emilia-Romagna"
    - "country code": "IT"
    You should see the following message: ~Generating 2,048 bit RSA key pair and self-signed certificate (SHA384withRSA) with a validity of 360 days\n for: CN=Enrico Benini, O=Benkio, L=Cesena, ST=Emilia-Romagna, C=IT~
  - Convert the keystore to PEM :: following the commands in the link above. eg:
    #+begin_src sh
      # multiple passwords will be requested. Just put the same "sbotsKeystorePassword" everywhere
      keytool -importkeystore -srckeystore sbotsKeystore.jks -destkeystore sbots.p12 -srcstoretype jks -deststoretype pkcs12
      openssl pkcs12 -in sbots.p12 -out sbotsCertificatePub.pem
    #+end_src

*** Deploy

 - Set the ~main/src/resources/application.conf~ accordingly:
   - ~webhook-base-url~ as ~https://<serverip>:<outsideport>~, eg ~https://129.152.27.196:8443~
   - ~host-url~ as ~0.0.0.0~
   - ~port~ as ~<internalPort>~ in our case ~8081~
   - ~webhook-certificate~ with the path of the public certificate, eg ~sbotsCertificatePub.pem~
   - ~keystore-path~ add the path to the keystore, eg ~sbotsKeystore.jks~
   - ~keystore-password~ add the password of the keystore, eg ~sbotsKeystorePassword~
 - Run ~sbt "clean; main/assembly"~ to create the fat jar
 - Move the fat jar to the VM by ~rsync~ and ~ssh~. Eg. ~rsync -P -e "ssh -i <<private key of the vm>>" <<path to the fat jar -> sBots/main/target/scala-2.13/main.jar>> <<user of the vm>>@<<public IP of the vm>>:/home/<<user of the vm>>/main.jar~ (~rsync -P -e "ssh -i ubuntu_rsa.pem" /home/benkio/workspace/sBots/main/target/scala-2.13/main.jar ubuntu@129.152.27.196:/home/ubuntu/bots/main.jar~)
 - Move the ~botDB.sqlite~ if not present in the same way before. If an update to the ~media~ needs to be done, better to dump the current database in order not to lose the ~timeout~, ~subscription~, or other changes in the process. No easy way to migrate the database as of now.
 - Login to the VM
 - OPTIONAL: be sure to have the right environment variables. IT'S RECOMMENDED TO
   CHANGE the ~application.conf~ (point 1) before running the ~assembly~. The environment variables could lose their value somehow.
 - Run the bots.
   - Polling: ~java -Xmx512m -Xms512m -cp main.jar com.benkio.main.MainPolling~
   - Webhook: ~java -Xmx512m -Xms512m -cp main.jar com.benkio.main.MainWebhook~
 - press ~Ctrl+Z~, run ~bg~ and ~disown~ in order to let previous command run in background
 - close your terminal and enjoy
