///////////////////////////////////////////////////////////////////////////////
//             Bot di Richard Benson, contains all the Benson's frases       //
///////////////////////////////////////////////////////////////////////////////
package root

import com.benkio.telegramBotInfrastructure._
import io.github.todokr.Emojipolation._
import com.benkio.telegramBotInfrastructure.model.{MediaFile, ReplyBundle, ReplyBundleMessage}

object RichardPHJBensonBot extends BotSkeleton {

  val messageRepliesAudioData : List[ReplyBundle] = List(
    ReplyBundleMessage(List("maledetto"                              ), List(MediaFile("maledetto.mp3"))),
    ReplyBundleMessage(List("io ti aiuto"                            ), List(MediaFile("aiuto.mp3"))),
    ReplyBundleMessage(List("assolo", "chitarra", "ghidarra"         ), List(MediaFile("assolo.mp3"))),
    ReplyBundleMessage(List("ci sei ritornata" , "ci sei ritornato"  ), List(MediaFile("ritornata.mp3"))),
    ReplyBundleMessage(List("anche la merda", "senza culo"           ), List(MediaFile("merda.mp3"))),
    ReplyBundleMessage(List("cobelini", "cobbolidi", "elfi",
      "nani", "la mandragola",
      "fico sacro", " la betulla", "la canfora",
      "le ossa dei morti"                                            ), List(MediaFile("figuremitologiche.mp3"))),
    ReplyBundleMessage(List("ma che cazzo sto dicendo", "il martell" ), List(MediaFile("machecazzostodicendo.mp3"))),
    ReplyBundleMessage(List("attenzione!!!", "attenzioneee"          ), List(MediaFile("attenzione.mp3"))),
    ReplyBundleMessage(List("poveri cretini", "poveri ignoranti"     ), List(MediaFile("povericretini.mp3"))),
    ReplyBundleMessage(List("ho capito", "ho gabido"                 ), List(MediaFile("hocapito.mp3"))),
    ReplyBundleMessage(List("avete capito", "avete gabido"           ), List(MediaFile("avetecapito.mp3"))),
    ReplyBundleMessage(List("feelings"                               ), List(MediaFile("feelings.mp3"))),
    ReplyBundleMessage(List("due ossa"                               ), List(MediaFile("dueossa.mp3"))),
    ReplyBundleMessage(List("proprio schifo"                         ), List(MediaFile("schifo.mp3"))),
    ReplyBundleMessage(List("pappalardo"                             ), List(MediaFile("pappalardo.mp3"))),
    ReplyBundleMessage(List("è un ordine"                            ), List(MediaFile("ordine.mp3"))),
    ReplyBundleMessage(List("una sera"                               ), List(MediaFile("sera.mp3"))),
    ReplyBundleMessage(List("il venerdì"                             ), List(MediaFile("venerdi.mp3"))),
    ReplyBundleMessage(List("oppura"                                 ), List(MediaFile("oppura.mp3"))),
    ReplyBundleMessage(List("volevo un pollo"                        ), List(MediaFile("pollo.mp3"))),
    ReplyBundleMessage(List("canzonette", "balera", "sagra",
      "condominiali", "piazza"                                ), List(MediaFile("canzonette.mp3")))
  )

  val messageRepliesGifsData : List[ReplyBundle]  = List(
    ReplyBundleMessage(List("vattene affanculo",
      "vattene a fanculo"                                  ), List(MediaFile("mavatteneaffanculo.gif"))),
    ReplyBundleMessage(List("rimpinzati",
      "cioccolata", "pandori", "gioggolada"                ), List(MediaFile("rimpinzati.gif"))),
    ReplyBundleMessage(List("pensa alla deficienza",
      "ma si può dire una cosa del genere"                 ), List(MediaFile("deficienza.gif"))),
    ReplyBundleMessage(List("pagare", "paga", "soldi", "bollette",
      "tasse",  "bolletta", "tassa"                        ), List(MediaFile("cacciaisoldi.gif"))),
    ReplyBundleMessage(List("fate come vi pare", "sti cazzi",
      "sti gazzi"                                          ), List(MediaFile("comevipare.gif"))),
    ReplyBundleMessage(List("ciao a tutti",
      "come state", "belle gioie"                          ), List(MediaFile("ciaocomestate.gif"))),
    ReplyBundleMessage(List("non sapere", "aristotele",
      "aristodele"                                         ), List(MediaFile("sodinonsapere.gif"))),
    ReplyBundleMessage(List("non ci credete?", "grande stronzata",
      "grande stronzate"                                   ), List(MediaFile("noncicredete.gif"))),
    ReplyBundleMessage(List("mi pare logico", "calcolo",
      "matematica", "loggigo"                              ), List(MediaFile("miparelogico.gif"))),
    ReplyBundleMessage(List("non me ne fotte", "chissenefrega",
      "non mi interessa"                                   ), List(MediaFile("nonmenefotte.gif"))),
    ReplyBundleMessage(List("certo", "escerto", "critiche",
      "non me ne frega un cazzo"                           ), List(MediaFile("escerto.gif"))),
    ReplyBundleMessage(List("levati dai coglioni",
      "fuori dai coglioni"                                 ), List(MediaFile("levatidaicoglioni.gif"))),
    ReplyBundleMessage(List("non sono coglione", "non sono mica coglione", "sarete coglioni voi",
      "sarete cojoni voi"                                  ), List(MediaFile("saretecoglionivoi.gif"))),
    ReplyBundleMessage(List("esperiment", "1, 2, 3",
      "uno, due, tre"                                      ), List(MediaFile("esperimento.gif"))),
    ReplyBundleMessage(List("bravo!!!", "bravooo"                 ), List(MediaFile("bravo.gif"))),
    ReplyBundleMessage(List("capolavoro"                          ), List(MediaFile("capolavoro.gif"))),
    ReplyBundleMessage(List(" metal"                              ), List(MediaFile("metal.gif"))),
    ReplyBundleMessage(List("allucinante"                         ), List(MediaFile("allucinante.gif"))),
    ReplyBundleMessage(List("mare di cazzate", "non è possibile"  ), List(MediaFile("nonépossibile.gif"))),
    ReplyBundleMessage(List("porca miseria"                       ), List(MediaFile("porcamiseria.gif"))),
    ReplyBundleMessage(List("schifoso!!!", "schifosooo"           ), List(MediaFile("schifoso.gif"))),
    ReplyBundleMessage(List("facendo soffrire"                    ), List(MediaFile("facendosoffrire.gif"))),
    ReplyBundleMessage(List("sentendo male"                       ), List(MediaFile("mistosentendomale.gif"))),
    ReplyBundleMessage(List("stare male"                          ), List(MediaFile("mifastaremale.gif"))),
    ReplyBundleMessage(List("lunghezza d'onda"                    ), List(MediaFile("lunghezzadonda.gif"))),
    ReplyBundleMessage(List("delirio"                             ), List(MediaFile("delirio.gif"))),
    ReplyBundleMessage(List("paradosso"                           ), List(MediaFile("paradosso.gif"))),
    ReplyBundleMessage(List("querelare", "guerelare"              ), List(MediaFile("querelare.gif"))),
    ReplyBundleMessage(List("cantate", "arigliano"                ), List(MediaFile("arigliano.gif"))),
    ReplyBundleMessage(List("non voglio nessuno"                  ), List(MediaFile("nonvoglionessuno.gif"))),
    ReplyBundleMessage(List("andati al cesso", "diecimila volte"  ), List(MediaFile("alcesso.gif"))),
    ReplyBundleMessage(List("non manca niente", "c'é tutto"       ), List(MediaFile("nonmancaniente.gif"))),
    ReplyBundleMessage(List("in fila"                             ), List(MediaFile("mettitiinfila.gif"))),
    ReplyBundleMessage(List("non male"                            ), List(MediaFile("nonmale.gif"))),
    ReplyBundleMessage(List("perché si sente"                     ), List(MediaFile("sisente.gif"))),
    ReplyBundleMessage(List("colpa vostra", "pazzo", "matto"      ), List(MediaFile("stodiventandopazzo.gif"))),
    ReplyBundleMessage(List("sorca", "lecciso", "figa"            ), List(MediaFile("sorcalecciso.gif"))),
    ReplyBundleMessage(List("non li sopporto", "che si deve fare" ), List(MediaFile("nonlisopporto.gif"))),
    ReplyBundleMessage(List("good", "show", "friends"             ), List(MediaFile("okgoodshowfriends.gif"))),
    ReplyBundleMessage(List("delus", "delud"                      ), List(MediaFile("deluso.gif"))),
    ReplyBundleMessage(List("chi cazzo sei"                       ), List(MediaFile("chicazzosei.gif"))),
    ReplyBundleMessage(List("feste"                               ), List(MediaFile("feste.gif"))),
    ReplyBundleMessage(List("si ostina", "foto vecchie"           ), List(MediaFile("ostina.gif"))),
    ReplyBundleMessage(List("vecchio", "vecchia"                  ), List(MediaFile("vecchio.gif"))),
    ReplyBundleMessage(List("venite qua"                          ), List(MediaFile("venitequa.gif"))),
    ReplyBundleMessage(List("sputo", "sputa"                      ), List(MediaFile("sputo.gif"))),
    ReplyBundleMessage(List("sorriso", emoji":smile:"             ), List(MediaFile("sorriso.gif"))),
    ReplyBundleMessage(List("lasciami in pace", "stronz"          ), List(MediaFile("lasciamiinpace.gif"))),
    ReplyBundleMessage(List("sono arrivato", "arivado", "piacere" ), List(MediaFile("arivado.gif"))),
    ReplyBundleMessage(List("pure bona"                           ), List(MediaFile("bona.gif"))),
    ReplyBundleMessage(List("mortacci vostri"                     ), List(MediaFile("mortaccivostri.gif"))),
    ReplyBundleMessage(List(" danza", "macabra", " ball"          ), List(MediaFile("danzamacabra.gif"))),
    ReplyBundleMessage(List("sei cambiat", "sei gambiat"          ), List(MediaFile("seicambiata.gif"))),
    ReplyBundleMessage(List("mio discapito", "disgabido"          ), List(MediaFile("discapito.gif"))),
    ReplyBundleMessage(List("peggio del peggio"                   ), List(MediaFile("peggiodelpeggio.gif"))),
    ReplyBundleMessage(List("cosa squallida", "abbia mai sentito" ), List(MediaFile("squallida.gif"))),
    ReplyBundleMessage(List("la verità"                           ), List(MediaFile("verita.gif"))),
    ReplyBundleMessage(List("ti dovresti vergognare"              ), List(MediaFile("tidovrestivergognare.gif"))),
    ReplyBundleMessage(List("oddio mio no", "dio mio no"          ), List(MediaFile("oddiomio.gif"))),
    ReplyBundleMessage(List("destino", "incontrare"               ), List(MediaFile("destino.gif"))),
    ReplyBundleMessage(List("meridionale", "terron"               ), List(MediaFile("meridionale.gif"))),
    ReplyBundleMessage(List("baci", "limonare", "peggio cose"     ), List(MediaFile("bacio.gif"))),
    ReplyBundleMessage(List("giudica"                             ), List(MediaFile("giudicate.gif"))),
    ReplyBundleMessage(List("ester", "esposito"                   ), List(MediaFile("ester.gif")))
  )

  val messageRepliesSpecialData : List[ReplyBundle] = List(
    ReplyBundleMessage(List("basta!!!", "bastaaa"                                            ), List(MediaFile("basta.mp3"), MediaFile("basta.gif"))),
    ReplyBundleMessage(List("ti devi spaventare"                                             ), List(MediaFile("tidevispaventare.mp3"), MediaFile("tidevispaventare.gif"))),
    ReplyBundleMessage(List("questa volta no"                                                ), List(MediaFile("questavoltano.mp3"), MediaFile("questavoltano.gif"))),
    ReplyBundleMessage(List("una vergogna"                                                   ), List(MediaFile("vergogna.mp3"), MediaFile("vergogna.gif"))),
    ReplyBundleMessage(List("mi devo trasformare", "cristo canaro"                           ), List(MediaFile("trasformista.mp3"), MediaFile("trasformista.gif"))),
    ReplyBundleMessage(List("masgus", "ma sgus", "ma scusa"                                  ), List(MediaFile("masgus.mp3"), MediaFile("masgus.gif"))),
    ReplyBundleMessage(List("gianni", "ciaoo"                                      ), List(MediaFile("grazie.mp3"), MediaFile("grazie.gif"))),
    ReplyBundleMessage(List("me ne vado"                                                     ), List(MediaFile("menevado.mp3"), MediaFile("menevado.gif"))),
    ReplyBundleMessage(List("stare attenti", "per strada"                                    ), List(MediaFile("incontrateperstrada.mp3"), MediaFile("incontrateperstrada.gif"))),
    ReplyBundleMessage(List("lavora tu vecchiaccia", "hai la pelle dura", "io sono creatura" ), List(MediaFile("lavoratu.mp3"), MediaFile("lavoratu.gif"))),
    ReplyBundleMessage(List("infernali!!!!", "infernaliii"                                   ), List(MediaFile("infernali.mp3"), MediaFile("infernali.gif"))),
    ReplyBundleMessage(List("per il culo"                                                    ), List(MediaFile("pigliandoperilculo.mp3"), MediaFile("pigliandoperilculo.gif"))),
    ReplyBundleMessage(List(emoji":lol:", emoji":rofl:"                                      ), List(MediaFile("risata.mp3"), MediaFile("risata.gif"))),
    ReplyBundleMessage(List("ammazza che sei", "quasi un frocio"                             ), List(MediaFile("frocio.mp3"), MediaFile("frocio.gif"))),
    ReplyBundleMessage(List("fammi questa cortesia"                                          ), List(MediaFile("fammiquestacortesia.mp3"), MediaFile("fammiquestacortesia.gif"))),
    ReplyBundleMessage(List("non mi sta bene"                                                ), List(MediaFile("nonmistabene.mp3"), MediaFile("nonmistabene.gif"))),
    ReplyBundleMessage(List("sai fare le labbra", "manco le labbra",
      "neanche le labbra"                                                             ), List(MediaFile("labbra.mp3"), MediaFile("labbra.gif"))),
    ReplyBundleMessage(List("la vita è il nemico"                                            ), List(MediaFile("vitanemico.mp3"), MediaFile("vitanemico.gif"))),
    ReplyBundleMessage(List("permettere"                                                     ), List(MediaFile("permettere.mp3"), MediaFile("permettere.gif"))),
    ReplyBundleMessage(List("le note"                                                        ), List(MediaFile("note.mp3"), MediaFile("note.gif"))),
    ReplyBundleMessage(List("viva napoli"                                                    ), List(MediaFile("vivanapoli.mp3"), MediaFile("vivaNapoli.gif")))
  )
}
