///////////////////////////////////////////////////////////////////////////////
//             Bot di Richard Benson, contains all the Benson's frases       //
///////////////////////////////////////////////////////////////////////////////
package root

import root.infrastructure._

import scala.concurrent.Future
import io.github.todokr.Emojipolation._

object RichardPHJBensonBot extends BotSkeleton {

  val messageRepliesAudioData : List[ReplyBundle] = List(
    ReplyBundle(List("maledetto"                              ), Mp3Files(List( "maledetto.mp3"))),
    ReplyBundle(List("io ti aiuto"                            ), Mp3Files(List( "aiuto.mp3"))),
    ReplyBundle(List("assolo", "chitarra", "ghidarra"         ), Mp3Files(List( "assolo.mp3"))),
    ReplyBundle(List("ci sei ritornata" , "ci sei ritornato"  ), Mp3Files(List( "ritornata.mp3"))),
    ReplyBundle(List("anche la merda", "senza culo"           ), Mp3Files(List( "merda.mp3"))),
    ReplyBundle(List("cobelini", "cobbolidi", "elfi",
      "nani", "la mandragola",
      "fico sacro", " la betulla", "la canfora",
      "le ossa dei morti"                                     ), Mp3Files(List( "figuremitologiche.mp3"))),
    ReplyBundle(List("ma che cazzo sto dicendo", "il martell" ), Mp3Files(List( "machecazzostodicendo.mp3"))),
    ReplyBundle(List("attenzione!!!", "attenzioneee"          ), Mp3Files(List( "attenzione.mp3"))),
    ReplyBundle(List("poveri cretini", "poveri ignoranti"     ), Mp3Files(List( "povericretini.mp3"))),
    ReplyBundle(List("ho capito", "ho gabido"                 ), Mp3Files(List( "hocapito.mp3"))),
    ReplyBundle(List("avete capito", "avete gabido"           ), Mp3Files(List( "avetecapito.mp3"))),
    ReplyBundle(List("feelings"                               ), Mp3Files(List( "feelings.mp3"))),
    ReplyBundle(List("due ossa"                               ), Mp3Files(List( "dueossa.mp3"))),
    ReplyBundle(List("proprio schifo"                         ), Mp3Files(List( "schifo.mp3"))),
    ReplyBundle(List("pappalardo"                             ), Mp3Files(List( "pappalardo.mp3"))),
    ReplyBundle(List("è un ordine"                            ), Mp3Files(List( "ordine.mp3"))),
    ReplyBundle(List("una sera"                               ), Mp3Files(List( "sera.mp3"))),
    ReplyBundle(List("il venerdì"                             ), Mp3Files(List( "venerdi.mp3"))),
    ReplyBundle(List("oppura"                                 ), Mp3Files(List( "oppura.mp3"))),
    ReplyBundle(List("volevo un pollo"                        ), Mp3Files(List( "pollo.mp3"))),
    ReplyBundle(List("canzonette", "balera", "sagra",
      "condominiali", "piazza"                                ), Mp3Files(List( "canzonette.mp3")))
  )

  val messageRepliesGifsData : List[ReplyBundle]  = List(
    ReplyBundle(List("bravo!!!", "bravooo"                 ), GifFiles(List( "bravo.gif"))),
    ReplyBundle(List("capolavoro"                          ), GifFiles(List( "capolavoro.gif"))),
    ReplyBundle(List(" metal"                              ), GifFiles(List( "metal.gif"))),
    ReplyBundle(List("allucinante"                         ), GifFiles(List( "allucinante.gif"))),
    ReplyBundle(List("mare di cazzate", "non è possibile"  ), GifFiles(List( "nonépossibile.gif"))),
    ReplyBundle(List("porca miseria"                       ), GifFiles(List( "porcamiseria.gif"))),
    ReplyBundle(List("schifoso!!!", "schifosooo"           ), GifFiles(List( "schifoso.gif"))),
    ReplyBundle(List("vattene affanculo",
      "vattene a fanculo"                                  ), GifFiles(List( "mavatteneaffanculo.gif"))),
    ReplyBundle(List("rimpinzati",
      "cioccolata", "pandori", "gioggolada"                ), GifFiles(List( "rimpinzati.gif"))),
    ReplyBundle(List("facendo soffrire"                    ), GifFiles(List( "facendosoffrire.gif"))),
    ReplyBundle(List("sentendo male"                       ), GifFiles(List( "mistosentendomale.gif"))),
    ReplyBundle(List("stare male"                          ), GifFiles(List( "mifastaremale.gif"))),
    ReplyBundle(List("lunghezza d'onda"                    ), GifFiles(List( "lunghezzadonda.gif"))),
    ReplyBundle(List("delirio"                             ), GifFiles(List( "delirio.gif"))),
    ReplyBundle(List("paradosso"                           ), GifFiles(List( "paradosso.gif"))),
    ReplyBundle(List("pensa alla deficienza",
      "ma si può dire una cosa del genere"                 ), GifFiles(List( "deficienza.gif"))),
    ReplyBundle(List("querelare", "guerelare"              ), GifFiles(List( "querelare.gif"))),
    ReplyBundle(List("cantate", "arigliano"                ), GifFiles(List( "arigliano.gif"))),
    ReplyBundle(List("non voglio nessuno"                  ), GifFiles(List( "nonvoglionessuno.gif"))),
    ReplyBundle(List("andati al cesso", "diecimila volte"  ), GifFiles(List( "alcesso.gif"))),
    ReplyBundle(List("ciao a tutti",
      "come state", "belle gioie"                          ), GifFiles(List( "ciaocomestate.gif"))),
    ReplyBundle(List("non manca niente", "c'é tutto"       ), GifFiles(List( "nonmancaniente.gif"))),
    ReplyBundle(List("in fila"                             ), GifFiles(List( "mettitiinfila.gif"))),
    ReplyBundle(List("non male"                            ), GifFiles(List( "nonmale.gif"))),
    ReplyBundle(List("perché si sente"                     ), GifFiles(List( "sisente.gif"))),
    ReplyBundle(List("non ci credete?", "grande stronzata",
      "grande stronzate"                                   ), GifFiles(List( "noncicredete.gif"))),
    ReplyBundle(List("colpa vostra", "pazzo", "matto"      ), GifFiles(List( "stodiventandopazzo.gif"))),
    ReplyBundle(List("mi pare logico", "calcolo",
      "matematica", "loggigo"                              ), GifFiles(List( "miparelogico.gif"))),
    ReplyBundle(List("sorca", "lecciso", "figa"            ), GifFiles(List( "sorcalecciso.gif"))),
    ReplyBundle(List("non li sopporto", "che si deve fare" ), GifFiles(List( "nonlisopporto.gif"))),
    ReplyBundle(List("ok", "good", "show", "friends"       ), GifFiles(List( "okgoodshowfriends.gif"))),
    ReplyBundle(List("delus", "delud"                      ), GifFiles(List( "deluso.gif"))),
    ReplyBundle(List("chi cazzo sei"                       ), GifFiles(List( "chicazzosei.gif"))),
    ReplyBundle(List("non me ne fotte", "chissenefrega",
      "non mi interessa"                                   ), GifFiles(List( "nonmenefotte.gif"))),
    ReplyBundle(List("feste"                               ), GifFiles(List( "feste.gif"))),
    ReplyBundle(List("si ostina", "foto vecchie"           ), GifFiles(List( "ostina.gif"))),
    ReplyBundle(List("non sapere", "aristotele",
      "aristodele"                                         ), GifFiles(List( "sodinonsapere.gif"))),
    ReplyBundle(List("vecchio", "vecchia"                  ), GifFiles(List( "vecchio.gif"))),
    ReplyBundle(List("pagare", "paga", "soldi", "bollette",
      "tasse",  "bolletta", "tassa"                        ), GifFiles(List("cacciaisoldi.gif"))),
    ReplyBundle(List("fate come vi pare", "sti cazzi",
      "sti gazzi"                                          ), GifFiles(List( "comevipare.gif"))),
    ReplyBundle(List("venite qua"                          ), GifFiles(List( "venitequa.gif"))),
    ReplyBundle(List("sputo", "sputa"                      ), GifFiles(List( "sputo.gif"))),
    ReplyBundle(List("certo", "escerto", "critiche",
      "non me ne frega un cazzo"                           ), GifFiles(List( "escerto.gif"))),
    ReplyBundle(List("sorriso", emoji":smile:"             ), GifFiles(List( "sorriso.gif"))),
    ReplyBundle(List("lasciami in pace", "stronz"          ), GifFiles(List( "lasciamiinpace.gif"))),
    ReplyBundle(List("sono arrivato", "arivado", "piacere" ), GifFiles(List( "arivado.gif"))),
    ReplyBundle(List("pure bona"                           ), GifFiles(List( "bona.gif"))),
    ReplyBundle(List("mortacci vostri"                     ), GifFiles(List( "mortaccivostri.gif"))),
    ReplyBundle(List(" danza", "macabra", " ball"          ), GifFiles(List( "danzamacabra.gif"))),
    ReplyBundle(List("sei cambiat", "sei gambiat"          ), GifFiles(List( "seicambiata.gif"))),
    ReplyBundle(List("levati dai coglioni",
      "fuori dai coglioni"                                 ), GifFiles(List( "levatidaicoglioni.gif"))),
    ReplyBundle(List("mio discapito", "disgabido"          ), GifFiles(List( "discapito.gif"))),
    ReplyBundle(List("peggio del peggio"                   ), GifFiles(List( "peggiodelpeggio.gif"))),
    ReplyBundle(List("non sono coglione", "non sono mica coglione", "sarete coglioni voi",
      "sarete cojoni voi"                                  ), GifFiles(List( "saretecoglionivoi.gif"))),
    ReplyBundle(List("cosa squallida", "abbia mai sentito" ), GifFiles(List( "squallida.gif"))),
    ReplyBundle(List("la verità"                           ), GifFiles(List( "verita.gif"))),
    ReplyBundle(List("ti dovresti vergognare"              ), GifFiles(List( "tidovrestivergognare.gif"))),
    ReplyBundle(List("oddio mio no", "dio mio no"          ), GifFiles(List( "oddiomio.gif"))),
    ReplyBundle(List("destino", "incontrare"               ), GifFiles(List( "destino.gif"))),
    ReplyBundle(List("meridionale", "terron"               ), GifFiles(List( "meridionale.gif"))),
    ReplyBundle(List("baci", "limonare", "peggio cose"     ), GifFiles(List( "bacio.gif"))),
    ReplyBundle(List("esperiment", "1, 2, 3",
      "uno, due, tre"                                      ), GifFiles(List( "esperimento.gif"))),
    ReplyBundle(List("giudica"                             ), GifFiles(List( "giudicate.gif"))),
    ReplyBundle(List("ester", "esposito"                   ), GifFiles(List( "ester.gif")))
  )

  val messageRepliesSpecialData : List[ReplyBundle] = List(
    ReplyBundle(List("basta!!!", "bastaaa"                                            ),MultimediaFiles(List("basta.mp3"),List("basta.gif"))),
    ReplyBundle(List("ti devi spaventare"                                             ), MultimediaFiles(List( "tidevispaventare.mp3"),List("tidevispaventare.gif"))),
    ReplyBundle(List("questa volta no"                                                ), MultimediaFiles(List( "questavoltano.mp3"),List("questavoltano.gif"))),
    ReplyBundle(List("una vergogna"                                                   ), MultimediaFiles(List( "vergogna.mp3"),List("vergogna.gif"))),
    ReplyBundle(List("mi devo trasformare", "cristo canaro"                           ), MultimediaFiles(List( "trasformista.mp3"),List("trasformista.gif"))),
    ReplyBundle(List("masgus", "ma sgus", "ma scusa"                                  ), MultimediaFiles(List( "masgus.mp3"),List("masgus.gif"))),
    ReplyBundle(List("grazie", "gianni", "ciaoo"                                      ), MultimediaFiles(List( "grazie.mp3"),List("grazie.gif"))),
    ReplyBundle(List("me ne vado"                                                     ), MultimediaFiles(List( "menevado.mp3"),List("menevado.gif"))),
    ReplyBundle(List("stare attenti", "per strada"                                    ), MultimediaFiles(List( "incontrateperstrada.mp3"),List("incontrateperstrada.gif"))),
    ReplyBundle(List("lavora tu vecchiaccia", "hai la pelle dura", "io sono creatura" ), MultimediaFiles(List( "lavoratu.mp3"),List("lavoratu.gif"))),
    ReplyBundle(List("infernali!!!!", "infernaliii"                                   ), MultimediaFiles(List( "infernali.mp3"),List("infernali.gif"))),
    ReplyBundle(List("per il culo"                                                    ), MultimediaFiles(List( "pigliandoperilculo.mp3"),List("pigliandoperilculo.gif"))),
    ReplyBundle(List(emoji":lol:", emoji":rofl:"                                      ), MultimediaFiles(List( "risata.mp3"),List("risata.gif"))),
    ReplyBundle(List("ammazza che sei", "quasi un frocio"                             ), MultimediaFiles(List( "frocio.mp3"),List("frocio.gif"))),
    ReplyBundle(List("fammi questa cortesia"                                          ), MultimediaFiles(List( "fammiquestacortesia.mp3"),List("fammiquestacortesia.gif"))),
    ReplyBundle(List("non mi sta bene"                                                ), MultimediaFiles(List( "nonmistabene.mp3"),List("nonmistabene.gif"))),
    ReplyBundle(List("sai fare le labbra", "manco le labbra",
      "neanche le labbra"                                                  ), MultimediaFiles(List( "labbra.mp3"),List("labbra.gif"))),
    ReplyBundle(List("la vita è il nemico"                                            ), MultimediaFiles(List( "vitanemico.mp3"),List("vitanemico.gif"))),
    ReplyBundle(List("permettere"                                                     ), MultimediaFiles(List( "permettere.mp3"),List("permettere.gif"))),
    ReplyBundle(List("le note"                                                        ), MultimediaFiles(List( "note.mp3"),List("note.gif"))),
    ReplyBundle(List("viva napoli"                                                    ), MultimediaFiles(List( "vivanapoli.mp3"),List("vivaNapoli.gif")))
  )
}
