package com.benkio.chatcore.model.show

import cats.implicits.*
import com.benkio.chatcore.conversions.YouTubeTimestamp.finiteDurationToYoutubeTimestamp
import com.benkio.chatcore.Arbitraries.given
import munit.FunSuite
import munit.ScalaCheckEffectSuite
import org.scalacheck.Prop.forAll

import scala.concurrent.duration.*

class ShowSpec extends FunSuite with ScalaCheckEffectSuite {

  test("show instance should render youtube url without timestamp when missing") {
    forAll { (show: Show) =>
      val baseShow = show.copy(timestamp = None)
      val expected =
        s"""${baseShow.uploadDate} - https://www.youtube.com/watch?v=${baseShow.id}
           | ${baseShow.title}
           |----------
           | ${baseShow.description.getOrElse("")}""".stripMargin
      assertEquals(baseShow.show, expected)
    }
  }

  test("show instance should render youtube url with timestamp query when present") {
    forAll { (show: Show) =>
      val showWithTimestamp = show.copy(timestamp = Some(1.hour + 2.minutes + 3.seconds))
      val expected          =
        s"""${show.uploadDate} - https://www.youtube.com/watch?v=${show.id}&t=1h2m3s
           | ${show.title}
           |----------
           | ${show.description.getOrElse("")}""".stripMargin
      assertEquals(showWithTimestamp.show, expected)
    }
  }

  test("show instance should include fields generated by Arbitrary[Show]") {
    forAll { (show: Show) =>
      val rendered = show.show
      assert(rendered.contains(show.uploadDate.toString))
      assert(rendered.contains(s"https://www.youtube.com/watch?v=${show.id}"))
      assert(rendered.contains(show.title))
      assert(rendered.contains(show.description.getOrElse("")))
      show.timestamp match {
        case Some(timestamp) =>
          assert(rendered.contains(s"&t=${finiteDurationToYoutubeTimestamp(timestamp)}"))
        case None =>
          assert(!rendered.contains("&t="))
      }
    }
  }
}
