package com.benkio.xahleebot

import cats.effect.Async
import com.benkio.telegrambotinfrastructure.BackgroundJobManager
import com.benkio.telegrambotinfrastructure.model.CommandTrigger
import com.benkio.telegrambotinfrastructure.model.MediaFile
import com.benkio.telegrambotinfrastructure.model.RandomSelection
import com.benkio.telegrambotinfrastructure.model.ReplyBundleCommand
import com.benkio.telegrambotinfrastructure.patterns.CommandPatterns.RandomLinkCommand
import com.benkio.telegrambotinfrastructure.patterns.CommandPatterns.SubscribeUnsubscribeCommand
import com.benkio.telegrambotinfrastructure.resources.db.DBLayer
import log.effect.LogWriter

object CommandRepliesData {

  def values[F[_]: Async](
      dbLayer: DBLayer[F],
      backgroundJobManager: BackgroundJobManager[F],
      botName: String
  )(implicit
      log: LogWriter[F]
  ): List[ReplyBundleCommand[F]] = List(
    RandomLinkCommand.searchShowReplyBundleCommand[F](
      dbShow = dbLayer.dbShow,
      botName = botName,
    ),
    SubscribeUnsubscribeCommand.subscribeReplyBundleCommand[F](
      backgroundJobManager = backgroundJobManager,
      botName = botName
    ),
    SubscribeUnsubscribeCommand.unsubscribeReplyBundleCommand[F](
      backgroundJobManager = backgroundJobManager,
      botName = botName
    ),
    SubscribeUnsubscribeCommand.subscriptionsReplyBundleCommand[F](
      dbSubscription = dbLayer.dbSubscription,
      backgroundJobManager = backgroundJobManager,
      botName = botName
    ),
    ReplyBundleCommand[F](
      trigger = CommandTrigger("ass"),
      reply = List(
        mf"xah_Asshole.mp3",
        mf"xah_CCppSucksStonkyAss.mp3",
        mf"xah_EmacsLispPainAss.mp3",
        mf"xah_FakingAss.mp3",
        mf"xah_GuideAss.mp3",
        mf"xah_IdiotAss.mp3",
        mf"xah_InstanceMyAss.mp3",
        mf"xah_MethodYourAss.mp3",
        mf"xah_MyAss.mp3",
        mf"xah_MyAss2.mp3",
        mf"xah_StonkyAssSucks.mp3",
        mf"xah_SuckLessYourAss-001.mp3",
        mf"xah_SuckLessYourAss.mp3",
        mf"xah_YourAss.mp3"
      ),
      replySelection = RandomSelection
    ),
    ReplyBundleCommand[F](
      trigger = CommandTrigger("ccpp"),
      reply = List(
        mf"xah_CCppFakhead.mp3",
        mf"xah_CCppJavaPythonPHPJavascriptWorstFak.mp3",
        mf"xah_CCppSucksStonkyAss.mp3",
        mf"xah_CFak.mp3",
        mf"xah_CFakhead-001.mp3",
        mf"xah_CFakhead.mp3",
        mf"xah_CIdiot.mp3",
        mf"xah_CProgrammersIdiots.mp3",
        mf"xah_CSyntaxWorstFak.mp3",
        mf"xah_CUnixCrap.mp3",
        mf"xah_CUnixIdiots.mp3",
        mf"xah_CWorstFak.mp3",
        mf"xah_CExtremeIdioticFak.mp3",
        mf"xah_WhyIHateCCppIdiocyFaks.mp3",
        mf"xah_HackerHateCUnixFak.mp3",
        mf"xah_FakAll.mp3",
        mf"xah_FakIdioticCUnix.mp3",
        mf"xah_JavascriptCCppCompilerFak.mp3",
        mf"xah_LaughCFakhead.mp3",
        mf"xah_LinuxCCppFakheads.mp3",
        mf"xah_ProgrammersCCppIdiots.mp3",
        mf"xah_UnixCIdiot.mp3"
      ),
      replySelection = RandomSelection
    ),
    ReplyBundleCommand[F](
      trigger = CommandTrigger("crap"),
      reply = List(
        mf"xah_BitmapCrap.mp3",
        mf"xah_CUnixCrap.mp3",
        mf"xah_CommonLispCrap.mp3",
        mf"xah_Crap-001.mp3",
        mf"xah_Crap-002.mp3",
        mf"xah_Crap-003.mp3",
        mf"xah_Crap-004.mp3",
        mf"xah_Crap.mp3",
        mf"xah_Crap2.mp3",
        mf"xah_Crap3.mp3",
        mf"xah_Crap4.mp3",
        mf"xah_Crap5.mp3",
        mf"xah_Crap6.mp3",
        mf"xah_Crap7.mp3",
        mf"xah_CrapShit.mp3",
        mf"xah_CrapShit2.mp3",
        mf"xah_DesignFakCrap.mp3",
        mf"xah_EmacsCalculatorShit.mp3",
        mf"xah_FakIdioticCUnix.mp3",
        mf"xah_GiveShit.mp3",
        mf"xah_IncomprehensibleShit.mp3",
        mf"xah_IntFloatCrap.mp3",
        mf"xah_NetscapeCrap.mp3",
        mf"xah_NodeJSCrapNPMFak.mp3",
        mf"xah_PythonShit.mp3",
        mf"xah_Shit-001.mp3",
        mf"xah_Shit.mp3",
        mf"xah_ShitCrap.mp3",
        mf"xah_ThirtyYearsFSFGNURichardStallmanUnixPhilosophyFakheadCrap.mp3",
        mf"xah_TwitterDramaShit.mp3",
        mf"xah_UnixCrap.mp3",
        mf"xah_UnixCrap2.mp3",
        mf"xah_UnixPhilosophyCrap.mp3"
      ),
      replySelection = RandomSelection
    ),
    ReplyBundleCommand[F](
      trigger = CommandTrigger("emacs"),
      reply = List(
        mf"xah_EmacsAlanMackenzieFak.mp3",
        mf"xah_EmacsCalculatorShit.mp3",
        mf"xah_EmacsEliteIdiots.mp3",
        mf"xah_EmacsFak.mp3",
        mf"xah_EmacsFakhead.mp3",
        mf"xah_EmacsIdiots.mp3",
        mf"xah_EmacsLispPainAss.mp3",
        mf"xah_FakAll.mp3",
        mf"xah_FakEmacs.mp3",
        mf"xah_FakRichardStallman.mp3",
        mf"xah_IdiotsLinuxVimEmacsFanaticts.mp3",
        mf"xah_FakfaceRichardStallman.mp3",
        mf"xah_RichardStallmanFakhead.mp3"
      ),
      replySelection = RandomSelection
    ),
    ReplyBundleCommand[F](
      trigger = CommandTrigger("fakhead"),
      reply = List(
        mf"xah_AlanMackenzieFakhead.mp3",
        mf"xah_CCppFakhead.mp3",
        mf"xah_CFakhead-001.mp3",
        mf"xah_CFakhead.mp3",
        mf"xah_EmacsFakhead-001.mp3",
        mf"xah_EmacsFakhead.mp3",
        mf"xah_Fakhead-001.mp3",
        mf"xah_Fakhead.mp3",
        mf"xah_JSStandardStyleFakhead.mp3",
        mf"xah_LaughCFakhead.mp3",
        mf"xah_LiarsFakhead.mp3",
        mf"xah_LinuxCCppFakheads.mp3",
        mf"xah_LinuxIdiotsFakheads.mp3",
        mf"xah_LinuxUnixFakheads.mp3",
        mf"xah_MacFanaticsFakhead.mp3",
        mf"xah_MillennialFakhead.mp3",
        mf"xah_MillennialIdiotsFakhead.mp3",
        mf"xah_OpensourceFakhead.mp3",
        mf"xah_OpensourceFakheads.mp3",
        mf"xah_ProgrammerUnixFakhead.mp3",
        mf"xah_PythonFakhead.mp3",
        mf"xah_PythonFanaticsFakhead.mp3",
        mf"xah_RacismSocialJusticeFakhead.mp3",
        mf"xah_RichardStallmanFakhead-001.mp3",
        mf"xah_RichardStallmanFakhead.mp3",
        mf"xah_RichardStallmanFakhead2.mp3",
        mf"xah_SocialJusticeFakhead-001.mp3",
        mf"xah_SocialJusticeFakhead.mp3",
        mf"xah_ThereWasFakhead.mp3",
        mf"xah_ThirtyYearsFSFGNURichardStallmanUnixPhilosophyFakheadCrap.mp3",
        mf"xah_UnixFakhead-001.mp3",
        mf"xah_UnixFakhead.mp3",
        mf"xah_UnixFakhead2.mp3",
        mf"xah_UnixHackFakheads.mp3",
        mf"xah_UnixLinuxFakhead.mp3",
        mf"xah_UnixLinuxFakhead2.mp3",
        mf"xah_UnixLinuxOpensourceFakheads.mp3",
        mf"xah_UnixPhilosophyFakhead-001.mp3",
        mf"xah_UnixPhilosophyFakhead.mp3",
        mf"xah_WindowMicrosoftFakhead.mp3",
        mf"xah_WindowsFakhead.mp3",
        mf"xah_WriteProgrammingLanguageFakhead.mp3",
        mf"xah_ZuckerbergFakface.mp3"
      ),
      replySelection = RandomSelection
    ),
    ReplyBundleCommand[F](
      trigger = CommandTrigger("fak"),
      reply = List(
        mf"xah_APIFak.mp3",
        mf"xah_AlanFak.mp3",
        mf"xah_AlanMackenzieFak.mp3",
        mf"xah_AlanMackenzieFak2.mp3",
        mf"xah_AlanMackenzieFakIdiotDimitriGutov.mp3",
        mf"xah_AltTabFak.mp3",
        mf"xah_BitmapFak.mp3",
        mf"xah_BloadedFak.mp3",
        mf"xah_CCppJavaPythonPHPJavascriptWorstFak.mp3",
        mf"xah_CFak.mp3",
        mf"xah_CSyntaxWorstFak.mp3",
        mf"xah_CWorstFak.mp3",
        mf"xah_ComplexityFak.mp3",
        mf"xah_CExtremeIdioticFak.mp3",
        mf"xah_HackerHateCUnixFak.mp3",
        mf"xah_WhyIHateCCppIdiocyFaks.mp3",
        mf"xah_DesignFak.mp3",
        mf"xah_EmacsAlanMackenzieFak.mp3",
        mf"xah_EmacsFak.mp3",
        mf"xah_FacebookGoogleFak.mp3",
        mf"xah_Fak-001.mp3",
        mf"xah_Fak.mp3",
        mf"xah_Fak2.mp3",
        mf"xah_Fak3.mp3",
        mf"xah_Fak4.mp3",
        mf"xah_FakAlanMackenzie.mp3",
        mf"xah_FakAll.mp3",
        mf"xah_FakCUnix.mp3",
        mf"xah_FakEmacs.mp3",
        mf"xah_FakFakingIdiocyLinux.mp3",
        mf"xah_FakGoogle.mp3",
        mf"xah_FakGoogle2.mp3",
        mf"xah_FakingGoogle.mp3",
        mf"xah_FakProgrammersUnix.mp3",
        mf"xah_FakRichardStallman.mp3",
        mf"xah_FakVivaldiUnix.mp3",
        mf"xah_IdiodicFakPython.mp3",
        mf"xah_FakVivaliOpensourceFakheads.mp3",
        mf"xah_FakX11.mp3",
        mf"xah_FakingAss.mp3",
        mf"xah_FakIdioticSite.mp3",
        mf"xah_FakingLinuxUnixIdiots.mp3",
        mf"xah_FakingShit.mp3",
        mf"xah_FakLisp.mp3",
        mf"xah_FanatismFak-001.mp3",
        mf"xah_FanatismFak.mp3",
        mf"xah_FourtyPercentFak-001.mp3",
        mf"xah_FourtyPercentFak.mp3",
        mf"xah_GNUNoUnixFak.mp3",
        mf"xah_GoFakYourself.mp3",
        mf"xah_GuidoVanRossumFak.mp3",
        mf"xah_HackerFanatismFak.mp3",
        mf"xah_IdioticFak.mp3",
        mf"xah_IncomprehensibleFak.mp3",
        mf"xah_IteratorEnumenatorOOPPythonFak.mp3",
        mf"xah_JargonFak.mp3",
        mf"xah_JavaTutorialWorstFak.mp3",
        mf"xah_JavascriptCCppCompilerFak.mp3",
        mf"xah_JavascriptFak.mp3",
        mf"xah_LaTeXFak.mp3",
        mf"xah_LaughLinuxFak.mp3",
        mf"xah_LinuxFakIdiots.mp3",
        mf"xah_LookAtThisFak.mp3",
        mf"xah_MarketingFak.mp3",
        mf"xah_MeaninglessFak.mp3",
        mf"xah_Memes.mp3",
        mf"xah_MillennialGenFak.mp3",
        mf"xah_MillennialGenZoomersFak.mp3",
        mf"xah_MillennialsFak.mp3",
        mf"xah_NetscapeFak.mp3",
        mf"xah_NoMarketingNoFanatismFak.mp3",
        mf"xah_NodeJSCrapNPMFak.mp3",
        mf"xah_OOPFak.mp3",
        mf"xah_OOPJavaFak.mp3",
        mf"xah_OhFak.mp3",
        mf"xah_OneAnnoyingFak.mp3",
        mf"xah_OpenSourceFanaticsFak.mp3",
        mf"xah_OpensourceFak.mp3",
        mf"xah_OperaGoogleAppleFak.mp3",
        mf"xah_OpersourceFanaticsFak.mp3",
        mf"xah_PrivateMessageFak.mp3",
        mf"xah_PythonDocWorstFak.mp3",
        mf"xah_PythonDocumentationFak.mp3",
        mf"xah_PythonExtremeIdiocyFak.mp3",
        mf"xah_RichardStallmanFak.mp3",
        mf"xah_ShutTheFakUp.mp3",
        mf"xah_SloppyFak.mp3",
        mf"xah_ThemeFak.mp3",
        mf"xah_ThemeFak2.mp3",
        mf"xah_ThisFak.mp3",
        mf"xah_ThreadFak.mp3",
        mf"xah_TwoInchScreenFak.mp3",
        mf"xah_UnixFak-001.mp3",
        mf"xah_UnixFak.mp3",
        mf"xah_UnixFak2.mp3",
        mf"xah_UnixFak3.mp3",
        mf"xah_UnixPhilosophyFak.mp3",
        mf"xah_UnixPhilosophyFak2.mp3",
        mf"xah_UnixWorstFak-001.mp3",
        mf"xah_UnixWorstFak.mp3",
        mf"xah_VivaliFak.mp3",
        mf"xah_VivaliFakOpensourceFakheads.mp3",
        mf"xah_WhateverCFak.mp3",
        mf"xah_WhateverFak.mp3",
        mf"xah_WindowsUIFak.mp3",
        mf"xah_WorstFak.mp3",
        mf"xah_X11Fak.mp3"
      ),
      replySelection = RandomSelection
    ),
    ReplyBundleCommand[F](
      trigger = CommandTrigger("idiocy"),
      reply = List(
        mf"xah_BashIdiocy.mp3",
        mf"xah_CompleteUnixIdiocy.mp3",
        mf"xah_DesignIdiocy.mp3",
        mf"xah_ExtremeIdiocy-001.mp3",
        mf"xah_ExtremeIdiocy.mp3",
        mf"xah_ExtremeIdiocy2.mp3",
        mf"xah_ExtremeIdiocy3.mp3",
        mf"xah_ExtremeIdiocy4.mp3",
        mf"xah_ExtremeIndustryIdiocy.mp3",
        mf"xah_FakFakingIdiocyLinux.mp3",
        mf"xah_FakingIdiocy.mp3",
        mf"xah_FakingIdiocy2.mp3",
        mf"xah_WhyIHateCCppIdiocyFaks.mp3",
        mf"xah_Idiocy.mp3",
        mf"xah_Idiocy2.mp3",
        mf"xah_LinuxIdiocy.mp3",
        mf"xah_OpensourceIdiocy.mp3",
        mf"xah_OperaIdiocy.mp3",
        mf"xah_PatientIdiocy.mp3",
        mf"xah_PythonExtremeIdiocyFak.mp3",
        mf"xah_PythonIdiocy.mp3",
        mf"xah_UnixIdiocy.mp3"
      ),
      replySelection = RandomSelection
    ),
    ReplyBundleCommand[F](
      trigger = CommandTrigger("idiots"),
      reply = List(
        mf"xah_AlanMackenzieIdiot-001.mp3",
        mf"xah_AlanMackenzieIdiot.mp3",
        mf"xah_AllIdiots.mp3",
        mf"xah_AppleIdiots.mp3",
        mf"xah_CIdiot.mp3",
        mf"xah_CProgrammersIdiots.mp3",
        mf"xah_CUnixIdiots.mp3",
        mf"xah_EmacsEliteIdiots.mp3",
        mf"xah_EmacsIdiots.mp3",
        mf"xah_ExtremeIdiot.mp3",
        mf"xah_ExtremeIdiots.mp3",
        mf"xah_FakingIdiots.mp3",
        mf"xah_FakingLinuxUnixIdiots.mp3",
        mf"xah_FirefoxIdiots.mp3",
        mf"xah_FloatPointersIdiots.mp3",
        mf"xah_GuidoVanRossumIdiot.mp3",
        mf"xah_GuidoVanRossumIdiot2.mp3",
        mf"xah_HackerTypesIdiots.mp3",
        mf"xah_Idiot-001.mp3",
        mf"xah_Idiot-002.mp3",
        mf"xah_Idiot.mp3",
        mf"xah_Idiot2.mp3",
        mf"xah_IdiotAss.mp3",
        mf"xah_Idiots-001.mp3",
        mf"xah_Idiots.mp3",
        mf"xah_Idiots2.mp3",
        mf"xah_Idiots3.mp3",
        mf"xah_Idiots4.mp3",
        mf"xah_Idiots5.mp3",
        mf"xah_Idiots6.mp3",
        mf"xah_IdiotsLinuxVimEmacsFanaticts.mp3",
        mf"xah_LaughIdiots.mp3",
        mf"xah_LinuxFakIdiots.mp3",
        mf"xah_LinuxIdiots.mp3",
        mf"xah_LinuxIdiots2.mp3",
        mf"xah_LinuxIdiots3.mp3",
        mf"xah_LinuxIdiots4.mp3",
        mf"xah_LinuxMostIdiots.mp3",
        mf"xah_LinuxUnixIdiots.mp3",
        mf"xah_MemesIdiot.mp3",
        mf"xah_MillenGenIdiots.mp3",
        mf"xah_MillennialGenIdiots.mp3",
        mf"xah_MillennialGenIdiots2.mp3",
        mf"xah_MillennialGenerationIdiots.mp3",
        mf"xah_MillennialIdiot-001.mp3",
        mf"xah_MillennialIdiot-002.mp3",
        mf"xah_MillennialIdiot.mp3",
        mf"xah_MillennialIdiots-001.mp3",
        mf"xah_MillennialIdiots.mp3",
        mf"xah_MillennialIdiotsFakhead.mp3",
        mf"xah_MillennialsGenIdiots3.mp3",
        mf"xah_NerdIdiots.mp3",
        mf"xah_NerdsIdiot.mp3",
        mf"xah_PlankIdiots.mp3",
        mf"xah_ProgrammerIdiots.mp3",
        mf"xah_ProgrammerIdiots2.mp3",
        mf"xah_ProgrammersCCppIdiots.mp3",
        mf"xah_PythonFanaticsIdiot.mp3",
        mf"xah_PythonIdiots-001.mp3",
        mf"xah_PythonIdiots.mp3",
        mf"xah_TechnoIdiots.mp3",
        mf"xah_UnixCIdiot.mp3",
        mf"xah_UnixIdiots-001.mp3",
        mf"xah_UnixIdiots.mp3",
        mf"xah_UnixIdiots2.mp3",
        mf"xah_UnixLinuxIdiots.mp3",
        mf"xah_UnixWindowsIdiots.mp3",
        mf"xah_VimIdiot.mp3",
        mf"xah_WhatIdiot.mp3",
        mf"xah_WhiteWesternIdiots.mp3",
        mf"xah_XahTrollIdiot.mp3"
      ),
      replySelection = RandomSelection
    ),
    ReplyBundleCommand[F](
      trigger = CommandTrigger("laugh"),
      reply = List(
        mf"xah_Laugh-001.mp3",
        mf"xah_Laugh-002.mp3",
        mf"xah_Laugh-003.mp3",
        mf"xah_Laugh-004.mp3",
        mf"xah_Laugh-005.mp3",
        mf"xah_Laugh-006.mp3",
        mf"xah_Laugh-007.mp3",
        mf"xah_Laugh-008.mp3",
        mf"xah_Laugh-009.mp3",
        mf"xah_Laugh-010.mp3",
        mf"xah_Laugh.mp3",
        mf"xah_Laugh10.mp3",
        mf"xah_Laugh11.mp3",
        mf"xah_Laugh12.mp3",
        mf"xah_Laugh13.mp3",
        mf"xah_Laugh14.mp3",
        mf"xah_Laugh15.mp3",
        mf"xah_Laugh16.mp3",
        mf"xah_Laugh2.mp3",
        mf"xah_Laugh3.mp3",
        mf"xah_Laugh4.mp3",
        mf"xah_Laugh5.mp3",
        mf"xah_Laugh6.mp3",
        mf"xah_Laugh7.mp3",
        mf"xah_Laugh8.mp3",
        mf"xah_Laugh9.mp3",
        mf"xah_LaughCFakhead.mp3",
        mf"xah_LaughIdiots.mp3",
        mf"xah_LaughLinuxFak.mp3"
      ),
      replySelection = RandomSelection
    ),
    ReplyBundleCommand[F](
      trigger = CommandTrigger("linux"),
      reply = List(
        mf"xah_FakFakingIdiocyLinux.mp3",
        mf"xah_FakingLinuxUnixIdiots.mp3",
        mf"xah_IdiotsLinuxVimEmacsFanaticts.mp3",
        mf"xah_LaughLinuxFak.mp3",
        mf"xah_LinuxCCppFakheads.mp3",
        mf"xah_LinuxFakIdiots.mp3",
        mf"xah_LinuxIdiocy.mp3",
        mf"xah_LinuxIdiots.mp3",
        mf"xah_LinuxIdiots2.mp3",
        mf"xah_LinuxIdiots3.mp3",
        mf"xah_LinuxIdiots4.mp3",
        mf"xah_LinuxIdiotsFakheads.mp3",
        mf"xah_LinuxMostIdiots.mp3",
        mf"xah_LinuxUnixFakheads.mp3",
        mf"xah_LinuxUnixFakheads2.mp3",
        mf"xah_LinuxUnixIdiots.mp3",
        mf"xah_UnixLinuxFakhead.mp3",
        mf"xah_UnixLinuxFakhead2.mp3",
        mf"xah_UnixLinuxIdiots.mp3",
        mf"xah_UnixLinuxOpensourceFakheads.mp3"
      ),
      replySelection = RandomSelection
    ),
    ReplyBundleCommand[F](
      trigger = CommandTrigger("millennial"),
      reply = List(
        mf"xah_MillenGenIdiots.mp3",
        mf"xah_MillenialGenerationFak.mp3",
        mf"xah_MillennialFakhead.mp3",
        mf"xah_MillennialGenFak.mp3",
        mf"xah_MillennialGenZoomersFak.mp3",
        mf"xah_MillennialGenIdiots.mp3",
        mf"xah_MillennialGenIdiots2.mp3",
        mf"xah_MillennialGenerationIdiots.mp3",
        mf"xah_MillennialIdiot-001.mp3",
        mf"xah_MillennialIdiot-002.mp3",
        mf"xah_MillennialIdiot.mp3",
        mf"xah_MillennialIdiots-001.mp3",
        mf"xah_MillennialIdiots.mp3",
        mf"xah_MillennialIdiotsFakhead.mp3",
        mf"xah_MillennialsFak.mp3",
        mf"xah_MillennialsGenIdiots3.mp3"
      ),
      replySelection = RandomSelection
    ),
    ReplyBundleCommand[F](
      trigger = CommandTrigger("opensource"),
      reply = List(
        mf"xah_FakVivaliOpensourceFakheads.mp3",
        mf"xah_OpenSourceFak.mp3",
        mf"xah_OpenSourceFak2.mp3",
        mf"xah_OpenSourceFanaticsFak.mp3",
        mf"xah_OpensourceFakhead.mp3",
        mf"xah_OpensourceFakheads.mp3",
        mf"xah_OpensourceIdiocy.mp3",
        mf"xah_OpersourceFanaticsFak.mp3",
        mf"xah_ThirtyYearsFSFGNURichardStallmanUnixPhilosophyFakheadCrap.mp3",
        mf"xah_UnixLinuxOpensourceFakheads.mp3",
        mf"xah_VivaliFakOpensourceFakheads.mp3"
      ),
      replySelection = RandomSelection
    ),
    ReplyBundleCommand[F](
      trigger = CommandTrigger("python"),
      reply = List(
        mf"xah_CCppJavaPythonPHPJavascriptWorstFak.mp3",
        mf"xah_FakAll.mp3",
        mf"xah_GuidoVanRossumFak.mp3",
        mf"xah_GuidoVanRossumIdiot.mp3",
        mf"xah_GuidoVanRossumIdiot2.mp3",
        mf"xah_IdiodicFakPython.mp3",
        mf"xah_IteratorEnumenatorOOPPythonFak.mp3",
        mf"xah_PythonDocWorstFak.mp3",
        mf"xah_PythonDocumentationFak.mp3",
        mf"xah_PythonDocumentationSucks.mp3",
        mf"xah_PythonExtremeIdiocyFak.mp3",
        mf"xah_PythonFakhead.mp3",
        mf"xah_PythonFanaticsFakhead.mp3",
        mf"xah_PythonFanaticsIdiot.mp3",
        mf"xah_PythonIdiocy.mp3",
        mf"xah_PythonIdiots-001.mp3",
        mf"xah_PythonIdiots.mp3",
        mf"xah_PythonShit.mp3",
        mf"xah_WhyPythonSucks.mp3"
      ),
      replySelection = RandomSelection
    ),
    ReplyBundleCommand[F](
      trigger = CommandTrigger("rantcompilation"),
      reply = List(
        mf"Xah3.mp3",
        mf"xah.mp3",
        mf"xah2.mp3",
        mf"xah4.mp3",
        mf"xah5.mp3"
      ),
      replySelection = RandomSelection
    ),
    ReplyBundleCommand[F](
      trigger = CommandTrigger("sucks"),
      reply = List(
        mf"xah_CCppSucksStonkyAss.mp3",
        mf"xah_ListComprehensionSucks.mp3",
        mf"xah_MacSucks.mp3",
        mf"xah_OperaSucks.mp3",
        mf"xah_PythonDocumentationSucks.mp3",
        mf"xah_StonkyAssSucks.mp3",
        mf"xah_SuckLessYourAss-001.mp3",
        mf"xah_SuckLessYourAss.mp3",
        mf"xah_WhyPythonSucks.mp3"
      ),
      replySelection = RandomSelection
    ),
    ReplyBundleCommand[F](
      trigger = CommandTrigger("unix"),
      reply = List(
        mf"xah_CUnixCrap.mp3",
        mf"xah_CUnixIdiots.mp3",
        mf"xah_CompleteUnixIdiocy.mp3",
        mf"xah_FakAll.mp3",
        mf"xah_FakProgrammersUnix.mp3",
        mf"xah_FakVivaldiUnix.mp3",
        mf"xah_FakingLinuxUnixIdiots.mp3",
        mf"xah_FakIdioticCUnix.mp3",
        mf"xah_HackerHateCUnixFak.mp3",
        mf"xah_WhyIHateCCppIdiocyFaks.mp3",
        mf"xah_GNUNoUnixFak.mp3",
        mf"xah_LinuxUnixFakheads.mp3",
        mf"xah_LinuxUnixFakheads2.mp3",
        mf"xah_LinuxUnixIdiots.mp3",
        mf"xah_ProgrammerUnixFakhead.mp3",
        mf"xah_ThirtyYearsFSFGNURichardStallmanUnixPhilosophyFakheadCrap.mp3",
        mf"xah_UnixCIdiot.mp3",
        mf"xah_UnixCrap.mp3",
        mf"xah_UnixCrap2.mp3",
        mf"xah_UnixFak-001.mp3",
        mf"xah_UnixFak.mp3",
        mf"xah_UnixFak2.mp3",
        mf"xah_UnixFak3.mp3",
        mf"xah_UnixFakhead-001.mp3",
        mf"xah_UnixFakhead.mp3",
        mf"xah_UnixHackFakheads.mp3",
        mf"xah_UnixIdiocy.mp3",
        mf"xah_UnixIdiots-001.mp3",
        mf"xah_UnixIdiots.mp3",
        mf"xah_UnixIdiots2.mp3",
        mf"xah_UnixLinuxFakhead.mp3",
        mf"xah_UnixLinuxFakhead2.mp3",
        mf"xah_UnixLinuxIdiots.mp3",
        mf"xah_UnixLinuxOpensourceFakheads.mp3",
        mf"xah_UnixPhilosophyCrap.mp3",
        mf"xah_UnixPhilosophyDispise.mp3",
        mf"xah_UnixPhilosophyFak-001.mp3",
        mf"xah_UnixPhilosophyFak.mp3",
        mf"xah_UnixPhilosophyFakhead-001.mp3",
        mf"xah_UnixPhilosophyFakhead.mp3",
        mf"xah_UnixWindowsIdiots.mp3",
        mf"xah_UnixWorstFak-001.mp3",
        mf"xah_UnixWorstFak.mp3"
      ),
      replySelection = RandomSelection
    ),
    ReplyBundleCommand[F](
      trigger = CommandTrigger("wtf"),
      reply = List(
        mf"xah_NoPictureWhatTheFak.mp3",
        mf"xah_WhatTheFak-001.mp3",
        mf"xah_WhatTheFak-002.mp3",
        mf"xah_WhatTheFak-003.mp3",
        mf"xah_WhatTheFak-004.mp3",
        mf"xah_WhatTheFak.mp3",
        mf"xah_WhatTheFak2.mp3",
        mf"xah_WhatTheFak3.mp3",
        mf"xah_WhatTheFak4.mp3",
        mf"xah_WhatTheFak5.mp3",
        mf"xah_WhatTheFak6.mp3",
        mf"xah_WhatTheFak7.mp3",
        mf"xah_WhyTheFak.mp3"
      ),
      replySelection = RandomSelection
    ),
    ReplyBundleCommand[F](
      trigger = CommandTrigger("extra"),
      reply = List(
        mf"xah_JesusOMG.mp3",
        mf"xah_BlaBlaShit.mp3"
      ),
      replySelection = RandomSelection
    ),
  )
}
