name: Auto approve & Auto Merge

on: pull_request_target

jobs:
  autoApproveMerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write-all
    if: startsWith(github.head_ref, 'update/')
    steps:
      - id: autoapprove
        name: autoapprove
        uses: hmarr/auto-approve-action@v3
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          MERGE_LABELS: ""
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_FILTER_AUTHOR: scala-steward
          MERGE_DELETE_BRANCH: "true"
          UPDATE_LABELS: ""
