name: Auto-merge
on: pull_request

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'update/')
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
