name: Auto-merge
on: pull_request

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'update/')
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: rebase
          token: ${{ steps.generate-token.outputs.token }}
