name: Auto approve & Auto Merge

on: pull_request_target

jobs:
  autoApproveMerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: startsWith(github.head_ref, 'update/')
    steps:
      - id: auto-approve
        name: Auto Approve
        uses: hmarr/auto-approve-action@v3
      - id: add-automerge-label
        name: Add automerge Label
        uses: TobKed/label-when-approved-action@v1.2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          label: 'automerge'
      - id: auto-merge
        name: Auto Merge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_FILTER_AUTHOR: scala-steward
