name: Download Prod DB

on:
  workflow_dispatch:

jobs:
  download-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: Download SQLite DB  Prod from VM
        run: |
           scp "ubuntu@${{ secrets.DEPLOY_SERVER_IP }}:/home/ubuntu/bots/botDB.sqlite3" ./botDB.sqlite3

      - name: Upload DB as artifact
        uses: actions/upload-artifact@v3
        with:
          name: prod sqlite-db
          path: botDB.sqlite3
