name: Download Prod DB

on:
  workflow_dispatch:

jobs:
  download-db:
    runs-on: ubuntu-latest

    steps:
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: Download SQLite DB  Prod from VM
        run: |
          rsync -av -e 'ssh -o StrictHostKeyChecking=no' ubuntu@${{ secrets.DEPLOY_SERVER_IP }}:/home/ubuntu/bots/botDB.sqlite3 /home/runner/work/botDB.sqlite3

      - name: Upload DB as artifact
        uses: actions/upload-artifact@v4
        with:
          name: prod sqlite-db
          path: /home/runner/work/botDB.sqlite3
