name: Download Prod DB

on:
  workflow_dispatch:

jobs:
  download-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: Download SQLite DB  Prod from VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "/home/ubuntu/bots/botDB.sqlite3"
          target: ./

      - name: Upload DB as artifact
        uses: actions/upload-artifact@v4
        with:
          name: prod sqlite-db
          path: botDB.sqlite3
