name: LinkCheck

on:
  workflow_dispatch:

jobs:
  LinkCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1
      - name: Check DB Links
        run: sbt checkAllLinksTest
