name: Scala CI

on:
  push:
    branches:
        - "**"
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Formatting
      run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: sbt "test"
  itTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Integration tests
      run: sbt "IntegrationTest/test"
  dependenciesUpdate:
    runs-on: ubuntu-latest
    if: startsWith( github.head_ref, 'update' )
    needs:
      - lint
      - test
      - itTest
    steps:
    - name: merge dependency update PRs
      uses: desbo/merge-pr-action@v0.3.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ALLOWED_UPDATE: any
