# This workflow will launch at 00:00 every Sunday
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

name: Launch Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  dependenciesUpdate:
    runs-on: ubuntu-latest
    # if: ${{ github.actor == 'github-actions[bot]' }}
    needs:
      - scala-steward
    steps:
    - name: merge dependency update PRs
      uses: desbo/merge-pr-action@v0.3.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ALLOWED_UPDATE: any
