name: Scala CI

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
        - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Formatting
      run: |
        echo this workflow was triggered by ${{github.actor}}
        sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: sbt "test"
  itTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Integration tests
      run: sbt "IntegrationTest/test"
  dependenciesUpdate:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'github-actions[bot]' }}
    needs:
      - lint
      - test
      - itTest
    steps:
    - name: merge dependency update PRs
      uses: desbo/merge-pr-action@v0.3.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ALLOWED_UPDATE: any
