name: Scala CI

on:
  push:
    branches:
        - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Formatting
      run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: sbt "telegramBotInfrastructure/test; richardPHJBensonBot/test; aBarberoBot/test; xahBot/test"
  itTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Integration tests
      run: sbt "telegramBotInfrastructure/IntegrationTest/test; richardPHJBensonBot/IntegrationTest/test; aBarberoBot/IntegrationTest/test; xahBot/IntegrationTest/test"
  dependenciesUpdate:
    runs-on: ubuntu-latest
    if: startsWith( github.head_ref, 'update' )
    needs:
      - lint
      - test
      - itTest
    steps:
    - name: merge dependency update PRs
      uses: desbo/merge-pr-action@v0.3.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ALLOWED_UPDATE: any
