name: Scala CI

on:
  push:
    branches:
        - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Formatting
      run: |
        echo this workflow was triggered by ${{github.actor}}
        sbt "undeclaredCompileDependenciesTest; scalafmtSbtCheck; scalafmtCheck; test:scalafmtCheck"
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: sbt "test"
  itTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Integration tests
      run: sbt "IntegrationTest/test"
