name: Scala CI

on:
  push:
    branches:
        - master
        - develop
  pull_request:
    branches:
        - master
        - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run telegramBotInfrastructure tests
      run: sbt telegramBotInfrastructure/test
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Formatting
      run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
  dependenciesUpdate:
    - name: merge dependency update PRs
      uses: desbo/merge-pr-action@v0.3.2
