name: Scala CI

on:
  push:
    branches:
        - "**"

jobs:
  lintAndTest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'sbt'
    - uses: sbt/setup-sbt@v1
    - name: Check Formatting, JSONs Validity, Explicit Dependencies
      run: |
        echo this workflow was triggered by ${{github.actor}}
        sbt "check"
        (cd filesCheck/ && npm run check && npm run lint)
    - name: Validate the Typescript Utility
      run: (cd filesCheck/ && npm run clean && npm run compile )
    - name: Validate the Scala project (clean, compile, format, test, itTest)
      run: sbt validate
