name: Scala CI

on:
  push:
    branches:
        - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Formatting
      run: |
        echo this workflow was triggered by ${{github.actor}}
        sbt "check"
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Validate the project (clean, compile, format, test, itTest
      run: sbt validate
