name: Scala CI

on:
  push:
    branches:
        - master
  pull_request:
    branches:
        - master
        - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run telegramBotInfrastructure tests
      run: sbt telegramBotInfrastructure/test
  itTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run botDB tests
      run: sbt botDB/IntegrationTest/test
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Formatting
      run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
  dependenciesUpdate:
    runs-on: ubuntu-latest
    if: startsWith( github.ref, 'refs/heads/update' )
    steps:
    - name: merge dependency update PRs
      uses: desbo/merge-pr-action@v0.3.2
